// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOu4ORLRK7w9Nu3B52_aEu6wPqPBmZ66A',
    appId: '1:593405336890:web:6a47ef6924c02812958403',
    messagingSenderId: '593405336890',
    projectId: 'baxify',
    authDomain: 'baxify.firebaseapp.com',
    storageBucket: 'baxify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp7WrIoSTjYpvvGJNqOVkqs3AmpTzCK_8',
    appId: '1:593405336890:android:ae0e598bc0cc352a958403',
    messagingSenderId: '593405336890',
    projectId: 'baxify',
    storageBucket: 'baxify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuESHGBv2UeuhD01o3dy7mTvcQYfXNKw4',
    appId: '1:593405336890:ios:cc05ef0b0b9c2a8d958403',
    messagingSenderId: '593405336890',
    projectId: 'baxify',
    storageBucket: 'baxify.appspot.com',
    iosClientId: '593405336890-rj32p40bbuh8pcadfk3j8soapg21btbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.baxify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuESHGBv2UeuhD01o3dy7mTvcQYfXNKw4',
    appId: '1:593405336890:ios:cc05ef0b0b9c2a8d958403',
    messagingSenderId: '593405336890',
    projectId: 'baxify',
    storageBucket: 'baxify.appspot.com',
    iosClientId: '593405336890-rj32p40bbuh8pcadfk3j8soapg21btbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.baxify',
  );
}
